### PR TITLE
Added option to new topic mode

### PR DESCRIPTION
**Pull request by hallard**
New features:

- Added Gateway heartbeat message sent limitation
- Added option to set extended topic `xiaomi/from/{{sid}}/{{cmd}}/{{model}}` that will allow filtering for subscribers
- Updated the according documentation

### CODE REVIEW

**Comment by cflurin** [comment]
Hi,
Thanks for your PR.
I'll have a look on my system and do some tests.

**Comment by hallard** [comment]
Hi,
no problem, should works but saw a strange thing with MQTT FX, under certain circonstance broker disconnected me when filtering by model, I don't know if it's related to my broker (MOSQUITTO) or my client (MQTTFX)

**xiaomi/from/+/+/sensor_ht/#**

All other filtering works well, strange.

**Comment by cflurin** [comment]
Hi,
I've quickly done some tests, so far it's okey.
1. I added a similar feature in [`homebridge-mqtt`](https://github.com/cflurin/homebridge-mqtt) and I'd like to handle it in the same way, I used `topic_type` `single` or `multiple`. `topic_mode` is also okey so you don't have to change that however the setting `from` and `to` are used to define the direction.
So would you please change the topic_mode settings to something like `short`, `full` and `both` or `multiple`, `single` and `both`.

2. I'd like to keep the README as simple as possible, the samples about filtering are mqtt features, I'd propose to move these examples to the Wiki and just add a link to the Wiki in README.

3. In your config.json examples you have to remove the last commas.
```
  "heartbeatfreq": 6,
```

You can use https://jsonlint.com/ to validate

**Comment by cflurin** [comment]
...
`Note this apply only to gateway heartbeat not the device's one.`

Devices also decrement the counter.
add this log.debug to see what happens:

``` 
    case "heartbeat":
    if (hb_count > 1) {
        log.debug('count '+hb_count+' model '+msg.model);
```

**Comment by hallard** [comment]
It's done:

- changed topic name of `from` to `short`
- fixed bug that filtered also no gateway device to send heartbeat  

please give a test, done that in a hurry ;-)

**Comment by cflurin** [comment]
1. Do you use the topic_mode both?
I think we don't need that, you can set topic_mode `full` and use mqtt this way:

`xiaomi/from/#`

2. Please remove the mqtt examples in the README as proposed above.

**Comment by hallard** [comment]
Yeah I agree and understand, but, I'm using both, to keep compatibility for old version that don't know the new features (and don't need) and if for example I'm using  `xiaomi/from/#`  and jeedom listening to `xiaomi/from` , will it work?

**Comment by cflurin** [comment]
Okey, let's keep the `both` setting, however it doesn't make sense to send the same data twice. It's better to change the subscriber topic.

**Pull request merged**
